scripts/do_ftrace: Improve script
Remove sudo commands in script
Improve error handling

Signed-off-by: Steve Jeong <steve@how2flow.net>

diff --git a/scripts/do_ftrace b/scripts/do_ftrace
--- a/scripts/do_ftrace
+++ b/scripts/do_ftrace
@@ -1,5 +1,7 @@
 #!/bin/bash
 
+set -e
+
 # ftracing script.
 # kernel function call stack. run with root permission.
 # check kernel config...
@@ -17,60 +19,67 @@ PREFIX=/sys/kernel/debug/tracing
 # evnet path
 E_IRQ=${PREFIX}/events/irq
 E_SCHD=${PREFIX}/events/sched
-E_SYS=${PREFIX}/evnets/syscalls
+E_SYS=${PREFIX}/events/syscalls
 
 # EUID
-if [[ ! -x "$(command -v sudo)" && $EUID -ne 0 ]]; then
+if [ $EUID -ne 0 ]; then
   echo "please run as 'root'"
   exit 1
 fi
 
-echo 0 | sudo tee "${PREFIX}/tracing_on"
+echo 0 | tee "${PREFIX}/tracing_on"
 sleep 1
 echo "tracing off"
 
-echo 0 | sudo tee "${PREFIX}/events/enable"
+echo 0 | tee "${PREFIX}/events/enable"
 sleep 1
 echo "events off"
 
-echo "function" | sudo tee "${PREFIX}/current_tracer"
+echo "function" | tee "${PREFIX}/current_tracer"
 sleep 1
 echo "function tracer enabled"
 
-echo "input example: \"hrtimer_interrupt\" (kernel function name.)"
+echo ""
 # filter check: $ cat /sys/kernel/debug/tracing/available_filter_functions
-read -r -p "input function filter:" filter
-echo ${filter} | sudo tee "${PREFIX}/set_ftrace_filter"
-[ ! "$?" == 0 ] && exit 1 # TODO: Handle exceptions more reliably.
+read -r -p "Enter the kernel function name to filter(e.g. hrtimer_interrupt): " filter
+echo ${filter} | tee "${PREFIX}/set_ftrace_filter"
+if [ ! "$?" == 0 ]; then # TODO: Handle exceptions more reliably.
+  echo "Invalid Function Filter.."
+  exit 1
+fi
 sleep 1
 echo "set_ftrace_filter enabled"
 
 # events
-echo 1 | sudo tee "${E_IRQ}/irq_handler_entry/enable"
-echo 1 | sudo tee "${E_IRQ}/irq_handler_exit/enable"
+echo 1 | tee "${E_IRQ}/irq_handler_entry/enable"
+echo 1 | tee "${E_IRQ}/irq_handler_exit/enable"
 echo "event enable"
 
-echo 1 | sudo tee "${PREFIX}/options/func_stack_trace"
-echo 1 | sudo tee "${PREFIX}/options/sym-offset"
+echo 1 | tee "${PREFIX}/options/func_stack_trace"
+echo 1 | tee "${PREFIX}/options/sym-offset"
 echo "function stack trace enabled"
 
-echo "input example: \"ls\" (input terminal command for call function stack.)"
-read -r -p "input trigger cmd:" cmd
-
+echo ""
+read -r -p "input trigger cmd(e.g. ls): " cmd
+if [ ! "$?" == 0 ]; then
+  exit 1
+fi
 echo "tracing on" # switch echo message for tracing only cmd.
-echo 1 | sudo tee "${PREFIX}/tracing_on"
+echo 1 | tee "${PREFIX}/tracing_on"
 
 echo "---cmd start---"
+echo "set filter: ${filter}"
+echo "test command: ${cmd}"
 ${cmd}
 echo "---cmd end---"
 
-echo 0 | sudo tee "${PREFIX}/tracing_on"
+echo 0 | tee "${PREFIX}/tracing_on"
 echo "tracing off"
 echo "tracing info..."
 sleep 3
 
-sudo cp "${PREFIX}/trace" .
+cp "${PREFIX}/trace" .
 mv trace trace.log
-sudo chmod +r trace.log
+chmod +r trace.log
 
 # vim: ft=sh ts=2 sw=2 sts=2 et
