DEVELOP GUI
Signed-off-by: Steve Jeong <steve@how2flow.net>

diff --git a/scripts/do_ftrace b/scripts/do_ftrace
--- a/scripts/do_ftrace
+++ b/scripts/do_ftrace
@@ -17,6 +17,8 @@
 
 set -e
 
+PARAM=${1}
+
 # ftracing script.
 # kernel function call stack. run with root permission.
 # check kernel config...
@@ -31,70 +33,89 @@ set -e
 # written by Steve Jeong (steve@how2flow.net).
 
 PREFIX=/sys/kernel/debug/tracing
-# evnet path
-E_IRQ=${PREFIX}/events/irq
-E_SCHD=${PREFIX}/events/sched
-E_SYS=${PREFIX}/events/syscalls
 
-# EUID
-if [ $EUID -ne 0 ]; then
-  echo "please run as 'root'"
-  exit 1
-fi
+prepare_events() {
+  local e_irq=${PREFIX}/events/irq
 
-echo 0 | tee "${PREFIX}/tracing_on"
-sleep 1
-echo "tracing off"
+  echo 1 | tee "${e_irq}/irq_handler_entry/enable"
+  echo 1 | tee "${e_irq}/irq_handler_exit/enable"
+  echo "event enable"
+  
+  echo 1 | tee "${PREFIX}/options/func_stack_trace"
+  echo 1 | tee "${PREFIX}/options/sym-offset"
+  echo "function stack trace enabled"
+}
 
-echo 0 | tee "${PREFIX}/events/enable"
-sleep 1
-echo "events off"
+prepare_tracing() {
+  echo 0 | tee "${PREFIX}/tracing_on"
+  sleep 1
+  echo "tracing off"
+  
+  echo 0 | tee "${PREFIX}/events/enable"
+  sleep 1
+  echo "events off"
+  
+  echo "function" | tee "${PREFIX}/current_tracer"
+  sleep 1
+  echo "function tracer enabled"
+}
 
-echo "function" | tee "${PREFIX}/current_tracer"
-sleep 1
-echo "function tracer enabled"
+main() {
+  local cmd=""
+  local filter=""
 
-echo ""
-# filter check: $ cat /sys/kernel/debug/tracing/available_filter_functions
-read -r -p "Enter the kernel function name to filter(e.g. hrtimer_interrupt): " filter
-echo ${filter} | tee "${PREFIX}/set_ftrace_filter"
-if [ ! "$?" == 0 ]; then # TODO: Handle exceptions more reliably.
-  echo "Invalid Function Filter.."
-  exit 1
-fi
-sleep 1
-echo "set_ftrace_filter enabled"
+  # EUID
+  if [ $EUID -ne 0 ]; then
+    echo "please run as 'root'"
+    exit 1
+  fi
 
-# events
-echo 1 | tee "${E_IRQ}/irq_handler_entry/enable"
-echo 1 | tee "${E_IRQ}/irq_handler_exit/enable"
-echo "event enable"
+  prepare_tracing
 
-echo 1 | tee "${PREFIX}/options/func_stack_trace"
-echo 1 | tee "${PREFIX}/options/sym-offset"
-echo "function stack trace enabled"
+  if [ ${PARAM} = "with-option" ]; then
+    echo ""
+    # filter check: $ cat /sys/kernel/debug/tracing/available_filter_functions
+    read -r -p "Enter the kernel function name to filter(e.g. hrtimer_interrupt): " filter
+    echo ${filter} | tee "${PREFIX}/set_ftrace_filter"
+    if [ ! "$?" == 0 ]; then # TODO: Handle exceptions more reliably.
+      echo "Invalid Function Filter.."
+      exit 1
+    fi
+    sleep 1
+    echo "set_ftrace_filter enabled"
+  elif [ ${PARAM} = "with-menu" ]; then
+    echo __FILTER_FUNC__ | tee "${PREFIX}/set_ftrace_filter"
+  fi
 
-echo ""
-read -r -p "input trigger cmd(e.g. ls): " cmd
-if [ ! "$?" == 0 ]; then
-  exit 1
-fi
-echo "tracing on" # switch echo message for tracing only cmd.
-echo 1 | tee "${PREFIX}/tracing_on"
+  prepare_events
 
-echo "---cmd start---"
-echo "set filter: ${filter}"
-echo "test command: ${cmd}"
-${cmd}
-echo "---cmd end---"
+  if [ ${PARAM} = "with-option" ]; then
+    echo ""
+    read -r -p "input trigger cmd(e.g. ls): " cmd
+    if [ ! "$?" == 0 ]; then
+      exit 1
+    fi
+  elif [ ${PARAM} = "with-menu" ]; then
+    cmd=__CMD__
+  fi
 
-echo 0 | tee "${PREFIX}/tracing_on"
-echo "tracing off"
-echo "tracing info..."
-sleep 3
+  echo 1 | tee "${PREFIX}/tracing_on"
+  echo "---cmd start---"
+  echo "set filter: ${filter}"
+  echo "test command: ${cmd}"
+  ${cmd}
+  echo "---cmd end---"
+  echo 0 | tee "${PREFIX}/tracing_on"
 
-cp "${PREFIX}/trace" .
-mv trace trace.log
-chmod +r trace.log
+  echo "tracing off"
+  echo "tracing info..."
+  sleep 3
+  
+  cp "${PREFIX}/trace" .
+  mv trace trace.log
+  chmod +r trace.log
+}
+
+main
 
 # vim: ft=sh ts=2 sw=2 sts=2 et
diff --git a/scripts/do_losetup b/scripts/do_losetup
--- a/scripts/do_losetup
+++ b/scripts/do_losetup
@@ -17,6 +17,8 @@
 
 set -e
 
+PARAM=${1}
+
 delete_block() {
   local workspace=()
 
@@ -36,45 +38,56 @@ delete_block() {
 }
 
 setup_block() {
-  local block="$(losetup -f)"
-  local cnt=0
+  local block=""
+  local cnt=""
   local idx=""
   local img_lists=()
+  local image=""
   local mnt=""
   local partitions=""
   local workspace=""
 
-  # Check Target file exists or not and print all.
-  workspace="$(ls *.img > /dev/null 2>&1)"
-  if [ ! $? -eq 0 ]; then
-    echo "There is no target file."
-    exit 1
-  else
-    img_lists=($(ls *img))
-    echo ""
-    echo "=== The List of Target files ==="
-    for i in ${img_lists[@]}; do
-      echo [${cnt}] ${i}
-      cnt=$((cnt + 1))
-    done
-  fi
-  # Select Target file
-  while true; do
-    echo ""
-    read -r -p "Select Target file number: " idx
-    if [[ "${idx}" =~ ^[0-9]+$ ]]; then
-      if [ ${idx} -ge 0 ] && [ ${idx} -lt ${#img_lists[@]} ]; then
-        break
-      else
-        echo "Invalid Target number! Please enter a valid number"
-      fi
-    else
-      echo "Invalid input! Please enter a valid number."
-    fi
-  done
+  if [ ${PARAM} = "with-option" ]; then
+    workspace=$(ls *.img > /dev/null 2>&1)
+    block=$(losetup -f)
 
-  losetup ${block} ${img_lists[${idx}]}
+    if [ ! $? -eq 0 ]; then
+      echo "There is no target file."
+      exit 1
+    else
+      img_lists=($(ls *img))
+      echo ""
+      echo "=== The List of Target files ==="
+      cnt=0
+      for i in ${img_lists[@]}; do
+        echo [${cnt}] ${i}
+        cnt=$((cnt + 1))
+      done
+    fi
+  
+    while true; do
+      echo ""
+      read -r -p "Select Target file number: " idx
+      if [[ "${idx}" =~ ^[0-9]+$ ]]; then
+        if [ ${idx} -ge 0 ] && [ ${idx} -lt ${#img_lists[@]} ]; then
+          break
+        else
+          echo "Invalid Target number! Please enter a valid number"
+        fi
+      else
+        echo "Invalid input! Please enter a valid number."
+      fi
+    done
+
+    image=${img_lists[${idx}]}
+  elif [ ${PARAM} = "with-menu" ]; then
+    block=__LOOP_DEVICE__
+    image=__IMAGE__
+  fi
+
+  losetup ${block} ${image}
   partx -v --add ${block}
+
   # Set mount point
   echo ""
   read -r -p "Make mount point(default: tmp{n}): " mnt
@@ -87,6 +100,7 @@ setup_block() {
     echo "So kernel-script automatically created a mount point with the following name..."
     echo "${mnt}"
   fi
+
   # Mount by partitions
   partitions="$(ls ${block}p* | wc -l)"
   for ((i=1; i<=${partitions}; i++)); do
@@ -98,12 +112,17 @@ setup_block() {
 main() {
   local option=""
 
-  read -r -p "Select option: losetup[s] or delete[d]? [s/d]: " option
+  if [ ${PARAM} = "with-option" ]; then
+    read -r -p "Select option: losetup[s] or delete[d]? [s/d]: " option
+  elif [ ${PARAM} = "with-menu" ]; then
+    option=__OPTION__
+  fi
+
   case ${option} in
-    [sS])
+    [sS]|setup)
       setup_block
       ;;
-    [dD])
+    [dD]|delete)
       delete_block
       ;;
     *)
